language: node_js
node_js:
  - "6"
install:
  - npm install bower
  - npm install
  - bower install
script:
  - npm test

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: false
  on: 
    branch: release